export const SELECTED_AUTHOR = 'SELECTED_AUTHOR';
export const SELECTED_SORTING_KEY = 'SELECTED_SORTING_KEY';
export const SELECTED_SORTING_ORDER = 'SELECTED_SORTING_ORDER';
export const SEARCH_BY_TITLE = 'SEARCH_BY_TITLE';
export const SELECTED_PAGE = 'SELECTED_PAGE';
export const SELECTED_ROWS_PER_PAGE = 'SELECTED_ROWS_PER_PAGE';
