export const SELECTED_AUTHOR = 'SELECTED_AUTHOR';
export const SELECTED_SORTING_KEY = 'SELECTED_SORTING_KEY';
export const SELECTED_SORTING_ORDER = 'SELECTED_SORTING_ORDER';
export const SEARCH_BY_TITLE = 'SEARCH_BY_TITLE';
